const services = Object.assign(
  {},
  require('./app-veyor.service'),
  require('./beerpay.service'),
  require('./bower.service'),
  require('./bundlephobia.service'),
  require('./cdnjs.service'),
  require('./circle-ci.service'),
  require('./codecov.service'),
  require('./codetally.service'),
  require('./npm.service'),
  require('./node.service'),
  require('./github.service'),
  require('./docker.service'),
  require('./david.service'),
  require('./coveralls.service'),
  require('./depfu.service'),
  require('./oss-tracker.service'),
  require('./packagist.service'),
  require('./jitpack.service'),
  require('./maven-central.service'),
  require('./travis.service'),
  require('./snyk-vulnerability.service'),
  require('./scrutinizer.service'),
  require('./requires-io.service'),
  require('./pypi.service'),
  require('./stackexchange.service'),
  require('./sourcegraph.service'),
);

module.exports = services;
